# Pandas. NumPy

## Задание 1.1

In [2]:
#Импортируйте библиотеку Numpy и дайте ей псевдоним np.
import numpy as np

In [100]:
#Создать одномерный массив Numpy под названием 
# a из 12 последовательных целых чисел чисел от 12 до 24 невключительно
a = np.arange(12,24,1)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [56]:
#Создать 5 двумерных массивов разной формы из массива a
#Не использовать в аргументах метода reshape число -1.
a1 = a.reshape((2,6))
a2 = a.reshape((3,4))
a3 = a.reshape((6,2))
a4 = a.reshape((4,3))
a5 = a.reshape((12,1))

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.
Создать 5 двумерных массивов разной формы из массива a. 
Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).


In [57]:
a1 = a.reshape((2,-1))
a2 = a.reshape((3,-1))
a3 = a.reshape((6,-1))
a4 = a.reshape((-1,3))
a5 = a.reshape((-1,1))

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?
Нет, так как размерность данного массива равна двум, 1 строка и 1 столбец

## Задание 1.2

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел 
с плавающей запятой из нормального распределения  со средним
, равным 0 и среднеквадратичным отклонением, равным 1.0. 

In [86]:
b =  np.random.rand(3,4)

Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [92]:
b_flat = b.flatten()
b_flat.shape

(12,)

## Задание 1.3

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0
невключительно с интервалом 2. 

In [97]:
c = np.arange(20, 0, -2)
c

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел
    , убывающих от 20 до 1 невключительно с интервалом 2. 

In [108]:
b = c.reshape(10,1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [109]:
#В чем разница между массивами a и b?
# Разница в форме массива, первый одномерный, а второй двумерный
c.shape, b.shape

((10,), (10, 1))

## Задание 1.4

Вертикально соединить массивы a и b. a - двумерный массив из нулей
, число строк которого больше 1 и на 1 меньше
, чем число строк двумерного массива b, состоящего из единиц.
Итоговый массив v должен иметь атрибут size, равный 10.


In [131]:
a = np.zeros((2,2))
b = np.ones((3,2))
v = np.vstack((a,b))
v, v.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), 10)

## Задание 1.5

Создать одномерный массив а, состоящий из последовательности
целых чисел от 0 до 12.
Поменять форму этого массива, чтобы получилась матрица A
(двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.


In [145]:
A = np.arange(0, 12, 1)
A = A.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Получить матрицу At путем транспонирования матрицы A.

In [146]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

Получить матрицу B, умножив матрицу A на матрицу At
с помощью матричного умножения.


In [148]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

Какой размер имеет матрица B? 

In [150]:
B.size

16

Получится ли вычислить обратную матрицу для матрицы B и почему?

In [152]:
np.linalg.inv(B)

LinAlgError: Singular matrix

Ошибка возникла потому, что в результате вышеприведенных действий получилась необратимая или вырожденная матрица, то есть определитель матрицы равен 0.  

In [193]:
np.linalg.det(B), B.shape

(0.0, (4, 4))

## Задание 1.6

Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.
Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 
Поменяйте его форму так, чтобы получилась квадратная матрица C. 
Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.


In [196]:
np.random.seed(42)
C = np.random.randint(0,16, 16)
C = CC.reshape(4,4)
#CC = np.random.randint(2, 10)
D = C + np.dot(B,10)
D

array([[  56,  143,  242,  334],
       [ 150,  507,  872, 1224],
       [ 236,  869, 1492, 2126],
       [ 330, 1230, 2127, 3024]])

Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [209]:
print("Определитель - ", round(np.linalg.det(D))) 
print("Ранг - ",np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print("Обратная матрица - ")
print(D_inv)

Определитель -  -1741608.0
Ранг -  4
Обратная матрица - 
[[ 0.135368   -0.09412681 -0.0250975   0.04079219]
 [-0.17297808  0.16351785  0.1740805  -0.16946638]
 [-0.05802224  0.09496052 -0.10651536  0.04285695]
 [ 0.09639712 -0.12303113  0.00685229  0.03466452]]


## Задание 1.7

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. 

In [211]:
for col in range(D_inv.shape[0]):
    for row in range(D_inv.shape[0]):
        D_inv[col][row] = 1 if  D_inv[col][row] >= 0 else 0
D_inv

array([[1., 0., 0., 1.],
       [0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [1., 0., 1., 1.]])

С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 
Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

In [216]:
np.where(D_inv, B,C)

array([[  5,   3,  12,  32],
       [ 10,  50,  86,   4],
       [  6,  86,   2, 212],
       [ 32,  10, 212, 302]])

Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C

## Задание 2

Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов.
Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.
Будем считать, что каждый столбец - это признак, а строка - наблюдение.
Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.
Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [231]:
a = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [232]:
mean_a = np.mean(a, axis = 1)
mean_a

array([2. , 8.4])

## Задание 3

Вычислите массив a_centered, отняв от значений массива а средние значения соответствующих признаков, содержащиеся в массиве mean_a.
Вычисление должно производиться в одно действие.
Получившийся массив должен иметь размер 5x2.

In [239]:
a_centered = a - mean_a.reshape(2,1)
a_centered

array([[-1. ,  0. ,  1. ,  1. , -1. ],
       [-2.4, -0.4,  2.6,  1.6, -1.4]])

## Задание 4

Найдите скалярное произведение столбцов массива a_centered.
В результате должна получиться величина a_centered_sp. 
Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [292]:
for i in range(a_centered.shape[1]):
    if i == 0:
        temp = np.array(a_centered.take(0, axis = 1))
    else:
        temp = temp * a_centered.take(i, axis = 1)
a_centered_sp = temp/(a_centered.shape[1]-1)
a_centered_sp
    

array([ 0.     , -1.39776])

## Задание 5

Число, которое мы получили в конце задания 3 является ковариацией двух признаков, содержащихся в массиве а. В задании 4 мы делили сумму произведений центрированных признаков на N-1, а не на N, поэтому полученная нами величина является несмещенной оценкой ковариации.
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. 
В качестве аргумента m функция np.cov должна принимать транспонированный массив a.
В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение 


In [303]:
np_cov = np.cov(a)
np_cov

array([[1. , 2. ],
       [2. , 4.3]])

# Pandas

In [305]:
import pandas as pd

## Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd.
Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные:
[1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price,в которых соответственно содержатся данные: 
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [310]:
authors  =  pd.DataFrame({'author_id':[1, 2, 3],
               'author_name':['Тургенев', 'Чехов', 'Островский']}
                         , columns=['author_id', 'author_name'])
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [314]:
book  =  pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
               'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                'price':[450, 300, 350, 500, 450, 370, 290]}
                , columns=['author_id', 'book_title','price'])
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

## Задание 2

Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [316]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

## Задание 3

Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [321]:
authors_price.sort_values(by='price',ascending = False ).head(5)

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

## Задание 4

Создайте датафрейм authors_stat на основе информации из authors_price.
В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price, в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.

In [342]:
authors_stat  = authors_price.groupby('author_name').agg({'price': ['min','max','mean']})
authors_stat = authors_stat.rename(columns={'max':'max_price','min':'max_price','mean':'mean_price'})
authors_stat

price                      
            max_price max_price  mean_price
author_name                                
Островский        290       370  330.000000
Тургенев          300       450  366.666667
Чехов             450       500  475.000000

## Задание 5

Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая.
В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.
Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке.Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая",а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями,при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl".Затем загрузите из этого файла датафрейм и назовите его book_info2.Удостоверьтесь, что датафреймы book_info и book_info2 идентичны


In [344]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [359]:
book_info  = pd.pivot_table(authors_price, values=['price'], index=['author_name'],
...                    columns = 'cover', aggfunc={'price': np.sum}, fill_value=0)
book_info

price        
cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950

In [360]:
book_info.to_pickle('book_info.pkl')

In [361]:
book_info2 = pd.read_pickle('book_info.pkl')
book_info2

price        
cover       мягкая твердая
author_name               
Островский     660       0
Тургенев       650     450
Чехов            0     950